version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: lab18-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5133236
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile.multi-stage
    container_name: lab18-nest
    restart: always
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 5133236
      DATABASE_NAME: postgres
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres_data:
