name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем исходный код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Настраиваем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Запускаем тесты
      - name: Run tests
        run: npm run test

      # 5. Сборка приложения
      - name: Build application
        run: npm run build

      # 6. Логин в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 7. Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t sukerayw/laba18-nestjs-app:latest .

      # 8. Пуш Docker-образа на Docker Hub
      - name: Push Docker image
        run: docker push sukerayw/laba18-nestjs-app:latest

      # 9. Деплой на Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "laba19-nestjs-app"
          heroku_email: "your_email@example.com"
